var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/Register/page.js")
R.c("server/chunks/ssr/_e37385a2._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0935222._.js")
R.c("server/chunks/ssr/_9a80fbb0._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8756e439._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__666f8ec1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2b5b0682._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_Register_page_actions_32146b8e.js")
R.m(66796)
module.exports=R.m(66796).exports
