var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/contact/page.js")
R.c("server/chunks/ssr/_14e3917b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d0935222._.js")
R.c("server/chunks/ssr/_1ef3b1b6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8756e439._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__666f8ec1._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__2b5b0682._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_contact_page_actions_44e32ac3.js")
R.m(10628)
module.exports=R.m(10628).exports
