1:"$Sreact.fragment"
2:I[97367,["/TurboDrive/_next/static/chunks/6fec836d06564579.js","/TurboDrive/_next/static/chunks/7f03f282c48e7a2c.js","/TurboDrive/_next/static/chunks/247eb132b7f7b574.js"],"ViewportBoundary"]
4:I[97367,["/TurboDrive/_next/static/chunks/6fec836d06564579.js","/TurboDrive/_next/static/chunks/7f03f282c48e7a2c.js","/TurboDrive/_next/static/chunks/247eb132b7f7b574.js"],"MetadataBoundary"]
5:"$Sreact.suspense"
0:{"buildId":"FDH_keCGMsHKMfP82b7Bx","rsc":["$","$1","h",{"children":[["$","meta",null,{"name":"robots","content":"noindex"}],["$","$L2",null,{"children":"$@3"}],["$","div",null,{"hidden":true,"children":["$","$L4",null,{"children":["$","$5",null,{"name":"Next.Metadata","children":"$@6"}]}]}],["$","meta",null,{"name":"next-size-adjust","content":""}]]}],"loading":null,"isPartial":false}
3:[["$","meta","0",{"charSet":"utf-8"}],["$","meta","1",{"name":"viewport","content":"width=device-width, initial-scale=1"}]]
6:[["$","title","0",{"children":"TurboDrive"}],["$","meta","1",{"name":"description","content":"Generated by create next app"}]]
